version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs:ro'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
    networks:
      - proxy-tier

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-docker-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-docker-gen
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs:rw'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  api:
    build: ./api
    container_name: api
    environment:
      - VIRTUAL_HOST=api.local
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=api.informaticslab.co.uk
      - LETSENCRYPT_EMAIL=alex.hilson@informaticslab.co.uk
    networks:
      - proxy-tier
volumes:
  nginx-config:
  nginx-certs:
  nginx-vhosts:
  nginx-webroot:

networks:
  proxy-tier:
    external:
      name: nginx-proxy

